# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/sirh3e/CLionProjects/vm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/sirh3e/CLionProjects/vm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/sirh3e/CLionProjects/vm/CMakeFiles /mnt/c/Users/sirh3e/CLionProjects/vm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/sirh3e/CLionProjects/vm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vm

# Build rule for target.
vm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vm
.PHONY : vm

# fast build rule for target.
vm/fast:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/build
.PHONY : vm/fast

src/instruction/add.o: src/instruction/add.c.o

.PHONY : src/instruction/add.o

# target to build an object file
src/instruction/add.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/add.c.o
.PHONY : src/instruction/add.c.o

src/instruction/add.i: src/instruction/add.c.i

.PHONY : src/instruction/add.i

# target to preprocess a source file
src/instruction/add.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/add.c.i
.PHONY : src/instruction/add.c.i

src/instruction/add.s: src/instruction/add.c.s

.PHONY : src/instruction/add.s

# target to generate assembly for a file
src/instruction/add.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/add.c.s
.PHONY : src/instruction/add.c.s

src/instruction/and.o: src/instruction/and.c.o

.PHONY : src/instruction/and.o

# target to build an object file
src/instruction/and.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/and.c.o
.PHONY : src/instruction/and.c.o

src/instruction/and.i: src/instruction/and.c.i

.PHONY : src/instruction/and.i

# target to preprocess a source file
src/instruction/and.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/and.c.i
.PHONY : src/instruction/and.c.i

src/instruction/and.s: src/instruction/and.c.s

.PHONY : src/instruction/and.s

# target to generate assembly for a file
src/instruction/and.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/and.c.s
.PHONY : src/instruction/and.c.s

src/instruction/dec.o: src/instruction/dec.c.o

.PHONY : src/instruction/dec.o

# target to build an object file
src/instruction/dec.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/dec.c.o
.PHONY : src/instruction/dec.c.o

src/instruction/dec.i: src/instruction/dec.c.i

.PHONY : src/instruction/dec.i

# target to preprocess a source file
src/instruction/dec.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/dec.c.i
.PHONY : src/instruction/dec.c.i

src/instruction/dec.s: src/instruction/dec.c.s

.PHONY : src/instruction/dec.s

# target to generate assembly for a file
src/instruction/dec.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/dec.c.s
.PHONY : src/instruction/dec.c.s

src/instruction/div.o: src/instruction/div.c.o

.PHONY : src/instruction/div.o

# target to build an object file
src/instruction/div.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/div.c.o
.PHONY : src/instruction/div.c.o

src/instruction/div.i: src/instruction/div.c.i

.PHONY : src/instruction/div.i

# target to preprocess a source file
src/instruction/div.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/div.c.i
.PHONY : src/instruction/div.c.i

src/instruction/div.s: src/instruction/div.c.s

.PHONY : src/instruction/div.s

# target to generate assembly for a file
src/instruction/div.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/div.c.s
.PHONY : src/instruction/div.c.s

src/instruction/halt.o: src/instruction/halt.c.o

.PHONY : src/instruction/halt.o

# target to build an object file
src/instruction/halt.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/halt.c.o
.PHONY : src/instruction/halt.c.o

src/instruction/halt.i: src/instruction/halt.c.i

.PHONY : src/instruction/halt.i

# target to preprocess a source file
src/instruction/halt.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/halt.c.i
.PHONY : src/instruction/halt.c.i

src/instruction/halt.s: src/instruction/halt.c.s

.PHONY : src/instruction/halt.s

# target to generate assembly for a file
src/instruction/halt.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/halt.c.s
.PHONY : src/instruction/halt.c.s

src/instruction/inc.o: src/instruction/inc.c.o

.PHONY : src/instruction/inc.o

# target to build an object file
src/instruction/inc.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/inc.c.o
.PHONY : src/instruction/inc.c.o

src/instruction/inc.i: src/instruction/inc.c.i

.PHONY : src/instruction/inc.i

# target to preprocess a source file
src/instruction/inc.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/inc.c.i
.PHONY : src/instruction/inc.c.i

src/instruction/inc.s: src/instruction/inc.c.s

.PHONY : src/instruction/inc.s

# target to generate assembly for a file
src/instruction/inc.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/inc.c.s
.PHONY : src/instruction/inc.c.s

src/instruction/load.o: src/instruction/load.c.o

.PHONY : src/instruction/load.o

# target to build an object file
src/instruction/load.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/load.c.o
.PHONY : src/instruction/load.c.o

src/instruction/load.i: src/instruction/load.c.i

.PHONY : src/instruction/load.i

# target to preprocess a source file
src/instruction/load.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/load.c.i
.PHONY : src/instruction/load.c.i

src/instruction/load.s: src/instruction/load.c.s

.PHONY : src/instruction/load.s

# target to generate assembly for a file
src/instruction/load.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/load.c.s
.PHONY : src/instruction/load.c.s

src/instruction/log.o: src/instruction/log.c.o

.PHONY : src/instruction/log.o

# target to build an object file
src/instruction/log.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/log.c.o
.PHONY : src/instruction/log.c.o

src/instruction/log.i: src/instruction/log.c.i

.PHONY : src/instruction/log.i

# target to preprocess a source file
src/instruction/log.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/log.c.i
.PHONY : src/instruction/log.c.i

src/instruction/log.s: src/instruction/log.c.s

.PHONY : src/instruction/log.s

# target to generate assembly for a file
src/instruction/log.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/log.c.s
.PHONY : src/instruction/log.c.s

src/instruction/mul.o: src/instruction/mul.c.o

.PHONY : src/instruction/mul.o

# target to build an object file
src/instruction/mul.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/mul.c.o
.PHONY : src/instruction/mul.c.o

src/instruction/mul.i: src/instruction/mul.c.i

.PHONY : src/instruction/mul.i

# target to preprocess a source file
src/instruction/mul.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/mul.c.i
.PHONY : src/instruction/mul.c.i

src/instruction/mul.s: src/instruction/mul.c.s

.PHONY : src/instruction/mul.s

# target to generate assembly for a file
src/instruction/mul.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/mul.c.s
.PHONY : src/instruction/mul.c.s

src/instruction/neg.o: src/instruction/neg.c.o

.PHONY : src/instruction/neg.o

# target to build an object file
src/instruction/neg.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/neg.c.o
.PHONY : src/instruction/neg.c.o

src/instruction/neg.i: src/instruction/neg.c.i

.PHONY : src/instruction/neg.i

# target to preprocess a source file
src/instruction/neg.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/neg.c.i
.PHONY : src/instruction/neg.c.i

src/instruction/neg.s: src/instruction/neg.c.s

.PHONY : src/instruction/neg.s

# target to generate assembly for a file
src/instruction/neg.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/neg.c.s
.PHONY : src/instruction/neg.c.s

src/instruction/or.o: src/instruction/or.c.o

.PHONY : src/instruction/or.o

# target to build an object file
src/instruction/or.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/or.c.o
.PHONY : src/instruction/or.c.o

src/instruction/or.i: src/instruction/or.c.i

.PHONY : src/instruction/or.i

# target to preprocess a source file
src/instruction/or.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/or.c.i
.PHONY : src/instruction/or.c.i

src/instruction/or.s: src/instruction/or.c.s

.PHONY : src/instruction/or.s

# target to generate assembly for a file
src/instruction/or.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/or.c.s
.PHONY : src/instruction/or.c.s

src/instruction/pop.o: src/instruction/pop.c.o

.PHONY : src/instruction/pop.o

# target to build an object file
src/instruction/pop.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/pop.c.o
.PHONY : src/instruction/pop.c.o

src/instruction/pop.i: src/instruction/pop.c.i

.PHONY : src/instruction/pop.i

# target to preprocess a source file
src/instruction/pop.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/pop.c.i
.PHONY : src/instruction/pop.c.i

src/instruction/pop.s: src/instruction/pop.c.s

.PHONY : src/instruction/pop.s

# target to generate assembly for a file
src/instruction/pop.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/pop.c.s
.PHONY : src/instruction/pop.c.s

src/instruction/push.o: src/instruction/push.c.o

.PHONY : src/instruction/push.o

# target to build an object file
src/instruction/push.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/push.c.o
.PHONY : src/instruction/push.c.o

src/instruction/push.i: src/instruction/push.c.i

.PHONY : src/instruction/push.i

# target to preprocess a source file
src/instruction/push.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/push.c.i
.PHONY : src/instruction/push.c.i

src/instruction/push.s: src/instruction/push.c.s

.PHONY : src/instruction/push.s

# target to generate assembly for a file
src/instruction/push.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/push.c.s
.PHONY : src/instruction/push.c.s

src/instruction/save.o: src/instruction/save.c.o

.PHONY : src/instruction/save.o

# target to build an object file
src/instruction/save.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/save.c.o
.PHONY : src/instruction/save.c.o

src/instruction/save.i: src/instruction/save.c.i

.PHONY : src/instruction/save.i

# target to preprocess a source file
src/instruction/save.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/save.c.i
.PHONY : src/instruction/save.c.i

src/instruction/save.s: src/instruction/save.c.s

.PHONY : src/instruction/save.s

# target to generate assembly for a file
src/instruction/save.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/save.c.s
.PHONY : src/instruction/save.c.s

src/instruction/shl.o: src/instruction/shl.c.o

.PHONY : src/instruction/shl.o

# target to build an object file
src/instruction/shl.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/shl.c.o
.PHONY : src/instruction/shl.c.o

src/instruction/shl.i: src/instruction/shl.c.i

.PHONY : src/instruction/shl.i

# target to preprocess a source file
src/instruction/shl.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/shl.c.i
.PHONY : src/instruction/shl.c.i

src/instruction/shl.s: src/instruction/shl.c.s

.PHONY : src/instruction/shl.s

# target to generate assembly for a file
src/instruction/shl.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/shl.c.s
.PHONY : src/instruction/shl.c.s

src/instruction/shr.o: src/instruction/shr.c.o

.PHONY : src/instruction/shr.o

# target to build an object file
src/instruction/shr.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/shr.c.o
.PHONY : src/instruction/shr.c.o

src/instruction/shr.i: src/instruction/shr.c.i

.PHONY : src/instruction/shr.i

# target to preprocess a source file
src/instruction/shr.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/shr.c.i
.PHONY : src/instruction/shr.c.i

src/instruction/shr.s: src/instruction/shr.c.s

.PHONY : src/instruction/shr.s

# target to generate assembly for a file
src/instruction/shr.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/shr.c.s
.PHONY : src/instruction/shr.c.s

src/instruction/sub.o: src/instruction/sub.c.o

.PHONY : src/instruction/sub.o

# target to build an object file
src/instruction/sub.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/sub.c.o
.PHONY : src/instruction/sub.c.o

src/instruction/sub.i: src/instruction/sub.c.i

.PHONY : src/instruction/sub.i

# target to preprocess a source file
src/instruction/sub.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/sub.c.i
.PHONY : src/instruction/sub.c.i

src/instruction/sub.s: src/instruction/sub.c.s

.PHONY : src/instruction/sub.s

# target to generate assembly for a file
src/instruction/sub.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/sub.c.s
.PHONY : src/instruction/sub.c.s

src/instruction/xor.o: src/instruction/xor.c.o

.PHONY : src/instruction/xor.o

# target to build an object file
src/instruction/xor.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/xor.c.o
.PHONY : src/instruction/xor.c.o

src/instruction/xor.i: src/instruction/xor.c.i

.PHONY : src/instruction/xor.i

# target to preprocess a source file
src/instruction/xor.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/xor.c.i
.PHONY : src/instruction/xor.c.i

src/instruction/xor.s: src/instruction/xor.c.s

.PHONY : src/instruction/xor.s

# target to generate assembly for a file
src/instruction/xor.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/instruction/xor.c.s
.PHONY : src/instruction/xor.c.s

src/vm.o: src/vm.c.o

.PHONY : src/vm.o

# target to build an object file
src/vm.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/vm.c.o
.PHONY : src/vm.c.o

src/vm.i: src/vm.c.i

.PHONY : src/vm.i

# target to preprocess a source file
src/vm.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/vm.c.i
.PHONY : src/vm.c.i

src/vm.s: src/vm.c.s

.PHONY : src/vm.s

# target to generate assembly for a file
src/vm.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/src/vm.c.s
.PHONY : src/vm.c.s

test/instruction/test_add.o: test/instruction/test_add.c.o

.PHONY : test/instruction/test_add.o

# target to build an object file
test/instruction/test_add.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/test/instruction/test_add.c.o
.PHONY : test/instruction/test_add.c.o

test/instruction/test_add.i: test/instruction/test_add.c.i

.PHONY : test/instruction/test_add.i

# target to preprocess a source file
test/instruction/test_add.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/test/instruction/test_add.c.i
.PHONY : test/instruction/test_add.c.i

test/instruction/test_add.s: test/instruction/test_add.c.s

.PHONY : test/instruction/test_add.s

# target to generate assembly for a file
test/instruction/test_add.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/test/instruction/test_add.c.s
.PHONY : test/instruction/test_add.c.s

test/instruction/test_and.o: test/instruction/test_and.c.o

.PHONY : test/instruction/test_and.o

# target to build an object file
test/instruction/test_and.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/test/instruction/test_and.c.o
.PHONY : test/instruction/test_and.c.o

test/instruction/test_and.i: test/instruction/test_and.c.i

.PHONY : test/instruction/test_and.i

# target to preprocess a source file
test/instruction/test_and.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/test/instruction/test_and.c.i
.PHONY : test/instruction/test_and.c.i

test/instruction/test_and.s: test/instruction/test_and.c.s

.PHONY : test/instruction/test_and.s

# target to generate assembly for a file
test/instruction/test_and.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/test/instruction/test_and.c.s
.PHONY : test/instruction/test_and.c.s

test/test.o: test/test.c.o

.PHONY : test/test.o

# target to build an object file
test/test.c.o:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/test/test.c.o
.PHONY : test/test.c.o

test/test.i: test/test.c.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.c.i:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/test/test.c.i
.PHONY : test/test.c.i

test/test.s: test/test.c.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.c.s:
	$(MAKE) -f CMakeFiles/vm.dir/build.make CMakeFiles/vm.dir/test/test.c.s
.PHONY : test/test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... vm"
	@echo "... src/instruction/add.o"
	@echo "... src/instruction/add.i"
	@echo "... src/instruction/add.s"
	@echo "... src/instruction/and.o"
	@echo "... src/instruction/and.i"
	@echo "... src/instruction/and.s"
	@echo "... src/instruction/dec.o"
	@echo "... src/instruction/dec.i"
	@echo "... src/instruction/dec.s"
	@echo "... src/instruction/div.o"
	@echo "... src/instruction/div.i"
	@echo "... src/instruction/div.s"
	@echo "... src/instruction/halt.o"
	@echo "... src/instruction/halt.i"
	@echo "... src/instruction/halt.s"
	@echo "... src/instruction/inc.o"
	@echo "... src/instruction/inc.i"
	@echo "... src/instruction/inc.s"
	@echo "... src/instruction/load.o"
	@echo "... src/instruction/load.i"
	@echo "... src/instruction/load.s"
	@echo "... src/instruction/log.o"
	@echo "... src/instruction/log.i"
	@echo "... src/instruction/log.s"
	@echo "... src/instruction/mul.o"
	@echo "... src/instruction/mul.i"
	@echo "... src/instruction/mul.s"
	@echo "... src/instruction/neg.o"
	@echo "... src/instruction/neg.i"
	@echo "... src/instruction/neg.s"
	@echo "... src/instruction/or.o"
	@echo "... src/instruction/or.i"
	@echo "... src/instruction/or.s"
	@echo "... src/instruction/pop.o"
	@echo "... src/instruction/pop.i"
	@echo "... src/instruction/pop.s"
	@echo "... src/instruction/push.o"
	@echo "... src/instruction/push.i"
	@echo "... src/instruction/push.s"
	@echo "... src/instruction/save.o"
	@echo "... src/instruction/save.i"
	@echo "... src/instruction/save.s"
	@echo "... src/instruction/shl.o"
	@echo "... src/instruction/shl.i"
	@echo "... src/instruction/shl.s"
	@echo "... src/instruction/shr.o"
	@echo "... src/instruction/shr.i"
	@echo "... src/instruction/shr.s"
	@echo "... src/instruction/sub.o"
	@echo "... src/instruction/sub.i"
	@echo "... src/instruction/sub.s"
	@echo "... src/instruction/xor.o"
	@echo "... src/instruction/xor.i"
	@echo "... src/instruction/xor.s"
	@echo "... src/vm.o"
	@echo "... src/vm.i"
	@echo "... src/vm.s"
	@echo "... test/instruction/test_add.o"
	@echo "... test/instruction/test_add.i"
	@echo "... test/instruction/test_add.s"
	@echo "... test/instruction/test_and.o"
	@echo "... test/instruction/test_and.i"
	@echo "... test/instruction/test_and.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

