//
// Created by sirh3e on 10/10/2020.
//

#ifndef VM_DEFAULTS_H
#define VM_DEFAULTS_H

#define VM_DEFAULT_DEBUG 1
#define VM_DEFAULT_STACK_ALLOCATED_SIZE 4096
#define VM_DEFAULT_INSTRUCTIONS_ALLOCATED_SIZE 4096

#endif //VM_DEFAULTS_H
