name: C CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: make cicd-clean
      run: make cicd-clean
    
    - name: make cicd-all
      run: make cicd-all

    - name: make cicd-check
      run: make cicd-check
