name: C CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: make clean
      run: make -j clean
    
    - name: make all
      run: make -j all

    - name: make check
      run: make -j check
